### ISSUE TITLE
what to pass to SimpleCollection constructor?

### ISSUE THREAD

**Issue by jonsavell** [swiesend/secret-service#23]
I was shocked to have been prompted for a password when I had clearly passed a password as an argument to the SimpleCollection constructor. When I look at the source code, it appears that there is some encryption occurring under the covers. How can I know what to pass to SimpleCollection so that no password prompt appears at runtime?

    private static final String COLLECTION_NAME = Main.class.getName();
    private static final String PASSWORD = "super-secret";

    public static void main(final String [] args) throws IOException {
        final String key = args[0];

        try (SimpleCollection collection = new SimpleCollection(COLLECTION_NAME, PASSWORD)) {
            collection.unlockWithUserPermission();

            try {
                Map<String, String> attributes = new HashMap<>();
                attributes.put(key, String.valueOf(key.hashCode()));
                List<String> items = collection.getItems(attributes);
                if (items != null && !items.isEmpty()) {
                    System.out.println("result: " + collection.getSecret(items.get(0)));
                }
            } finally {
                collection.lock();
            }
        }

        System.out.println("no result");
        System.exit(0);
    }

**Comment by swiesend** [comment]
I think the easiest would be not to use `collection.unlockWithUserPermission();`, as custom collections uses the internal `withoutPrompt.unlockWithMasterPassword()` method. One does not need to unlock a collection explicitly. The `unlockWithUserPermission()` exists only to unlock the default collection with a prompt for the first time of a session.

But I could provoke the behaviour, to be prompted for the master password of the custom collection with the option to store it in the default collection. I think the behaviour of the Secret Service API is somewhat inconsistent in that regard.

So store an item with a secret an retrieve it:
```java
class Main {

    private static final String COLLECTION_NAME = Main.class.getName();
    private static final String PASSWORD = "super-secret";

    public static void main(final String [] args) throws IOException {
        final String key = args[0];

        try (SimpleCollection collection = new SimpleCollection(COLLECTION_NAME, PASSWORD)) {

            Map<String, String> attributes = new HashMap<>();
            attributes.put(key, String.valueOf(key.hashCode()));

            // create and forget
            collection.createItem("My Item", "secret", attributes);

            try {
                List<String> items = collection.getItems(attributes);
                if (items != null && !items.isEmpty()) {
                    System.out.println("result: " + new String(collection.getSecret(items.get(0))));
                }
            } finally {
                collection.lock();
            }
        }

        System.out.println("no result");
        System.exit(0);
    }
}
```

**Comment by swiesend** [comment]
I handled the master password incorrect for already created collections.

Now this should be fixed with the new version `1.2.1` I just released and it should not make any difference, if you use `unlockWithUserPermission()` or not.

Please report me if there is still any issue.

**Comment by jonsavell** [comment]
Thank you for responding! I truly appreciate that.

I tried the code that you supplied, but I am still getting prompted for a password and I need to avoid that prompt. I have an application that is deployed to a server where there is no display. I am attempting to use Keyring as a persistent store for application data. I readily admit that it is not intended for this but it is my requirement.

Any suggestions for how to use the API using a single password embedded in code (and suppress the password prompts) would be most appreciated. Thank you in advance.
